from django import forms
class StudentRegistration(forms.Form):
    # name = forms.CharField(initial = "Ashish" , help_text = "name me keval ashish hi likhe ")
    # name = forms.CharField(label = 'Your name' , required =True , label_suffix = '' , initial = 'Swet' , disabled = True , help_text = 'limit 2 char')
    # name = forms.CharField(widget = forms.PasswordInput())
    # name = forms.CharField(widget = forms.URLInput())
    # name = forms.CharField(widget = forms.Textarea())
    # name = forms.CharField(widget = forms.HiddenInput())
    # name = forms.CharField(widget = forms.CheckboxInput())
    # name = forms.CharField(widget = forms.FileInput())
    # name = forms.CharField(widget = forms.TextInput(attrs = {'class' : 'Somecss1', 'id' : 'uniqueid'}))
    name = forms.CharField()
    email = forms.EmailField()
    password  = forms.CharField(widget = forms.PasswordInput())
    # email = forms.EmailField()
    # first_name = forms.CharField()
    # last_name = forms.CharField()
    # mobile = forms.IntegerField()
    # key = forms.CharField(widget = forms.HiddenInput())