# Generated by Django 5.1.4 on 2025-01-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stuemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stuname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stupass',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuid',
        ),
    ]
